Ctvrtek/Hackathon2/Controllers/EmergenciesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hackathon2.Models;
using TinyCsvParser;
using Hackathon2.Data;
using System.Text;
namespace Hackathon2.Controllers
{
    public class EmergenciesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmergenciesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Emergencies
        public async Task<IActionResult> Index()
        {
            var result = await _context.Emergency.ToListAsync();
            ViewData["Count"] = result.Count;
            return View(result);
        }

        // GET: Emergencies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emergency = await _context.Emergency
                .FirstOrDefaultAsync(m => m.Id == id);
            if (emergency == null)
            {
                return NotFound();
            }

            return View(emergency);
        }

        // GET: Emergencies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Emergencies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Type,Group,OkresCode,OkresName,ObecCode,ObecName,ProviderName,Address,AddressCode,OpenHours")] Emergency emergency)
        {
            if (ModelState.IsValid)
            {
                _context.Add(emergency);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(emergency);
        }

        // GET: Emergencies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emergency = await _context.Emergency.FindAsync(id);
            if (emergency == null)
            {
                return NotFound();
            }
            return View(emergency);
        }

        // POST: Emergencies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Type,Group,OkresCode,OkresName,ObecCode,ObecName,ProviderName,Address,AddressCode,OpenHours")] Emergency emergency)
        {
            if (id != emergency.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(emergency);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmergencyExists(emergency.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(emergency);
        }

        // GET: Emergencies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emergency = await _context.Emergency
                .FirstOrDefaultAsync(m => m.Id == id);
            if (emergency == null)
            {
                return NotFound();
            }

            return View(emergency);
        }

        // POST: Emergencies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var emergency = await _context.Emergency.FindAsync(id);
            _context.Emergency.Remove(emergency);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmergencyExists(int id)
        {
            return _context.Emergency.Any(e => e.Id == id);
        }
        public async Task<IActionResult> ParseData()
        {
            CsvParserOptions csvParserOptions = new CsvParserOptions(true, ',');
            CsvEmergencyMapping csvMapper = new CsvEmergencyMapping();
            CsvParser<Emergency> csvParser = new CsvParser<Emergency>(csvParserOptions, csvMapper);

            var result = csvParser
                .ReadFromFile(@"Data\LPS.csv", Encoding.ASCII)
                .ToList();

            foreach (var item in result)
            {
                if (item.Result.AddressCode == 0)
                {
                    item.Result.AddressCode = 0;
                }
            }
            foreach (var item in result) {
                _context.Emergency.Add(item.Result);
            }
            await _context.SaveChangesAsync();



            return RedirectToAction("Index");
        }
    }
}

Ctvrtek/Hackathon2/Controllers/PharmaciesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hackathon2.Models;
using Hackathon2.Data;
using TinyCsvParser;
using System.Text;

namespace Hackathon2.Controllers
{
    public class PharmaciesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PharmaciesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pharmacies
        public async Task<IActionResult> Index()
        {
            var result = await _context.Pharmacies.ToListAsync();
            ViewData["Count"] = result.Count;
            return View(result);
        }
        [HttpGet]
        public IEnumerable<Pharmacies> GetShows()
        {
            /*var data = new List<APIViewModel>();
            var shows = new List<Show>();
            foreach (var item in _context.TVs.Include(x => x.Timelines).ThenInclude(x => x.Shows))
            {

            }*/
            //var data = _context.Pharmacies.Include(x => x.Timelines).ThenInclude(x => x.Shows);
            return _context.Pharmacies.ToList();
        }
        [HttpGet]
        public JsonResult GetPharmacy(int id)
        {
            //var pharmacies = _context.Pharmacies
            //    .FirstOrDefaultAsync(m => m.Id == id);
            var result = _context.Pharmacies.ToList().FirstOrDefault(m => m.Id == id);
            /*var data = new List<APIViewModel>();
            var shows = new List<Show>();
            foreach (var item in _context.TVs.Include(x => x.Timelines).ThenInclude(x => x.Shows))
            {

            }*/
            //var data = _context.Pharmacies.Include(x => x.Timelines).ThenInclude(x => x.Shows);
            return new JsonResult(result);
        }
        // GET: Pharmacies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pharmacies = await _context.Pharmacies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pharmacies == null)
            {
                return NotFound();
            }

            return View(pharmacies);
        }

        // GET: Pharmacies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pharmacies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Address,Pharmacist,PharmacyCode,ICZ,PlaceCode,City,PostCode,Email,Website,Phone,PhoneNumber")] Pharmacies pharmacies)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pharmacies);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pharmacies);
        }

        // GET: Pharmacies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pharmacies = await _context.Pharmacies.FindAsync(id);
            if (pharmacies == null)
            {
                return NotFound();
            }
            return View(pharmacies);
        }

        // POST: Pharmacies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address,Pharmacist,PharmacyCode,ICZ,PlaceCode,City,PostCode,Email,Website,Phone,PhoneNumber")] Pharmacies pharmacies)
        {
            if (id != pharmacies.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pharmacies);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PharmaciesExists(pharmacies.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pharmacies);
        }

        // GET: Pharmacies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pharmacies = await _context.Pharmacies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pharmacies == null)
            {
                return NotFound();
            }

            return View(pharmacies);
        }

        // POST: Pharmacies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pharmacies = await _context.Pharmacies.FindAsync(id);
            _context.Pharmacies.Remove(pharmacies);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PharmaciesExists(int id)
        {
            return _context.Pharmacies.Any(e => e.Id == id);
        }
        public async Task<IActionResult> ParseData()
        {
            CsvParserOptions csvParserOptions = new CsvParserOptions(true, ',');
            CsvPersonMapping csvMapper = new CsvPersonMapping();
            CsvParser<Pharmacies> csvParser = new CsvParser<Pharmacies>(csvParserOptions, csvMapper);


            var result = csvParser
                .ReadFromFile(@"Data\lekarny.csv", Encoding.ASCII)
                .ToList();
            foreach (var item in result)
            {
                _context.Pharmacies.Add(item.Result);
            }
            await _context.SaveChangesAsync();



            return RedirectToAction("Index");
        }
    }
}

Ctvrtek/Hackathon2/Views/Shared/_Layout-copy.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hackathon</title>

    <environment include="Development">
        <link rel="stylesheet" href="https://bootswatch.com/3/lumen/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Hackathon</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Hackathon</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Ctvrtek/Hackathon2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - Hackathon</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <!-- Bulma Version 0.7.4-->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <script src="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/build/ol.js"></script>
    <link rel="stylesheet" type="text/css" href="~/css/admin.css">
    <link rel="stylesheet" type="text/css" href="~/css/style.css">
    <link rel="stylesheet" href="https://unpkg.com/bulma@0.7.4/css/bulma.min.css" />
    <link rel="stylesheet" href="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/css/ol.css" type="text/css">
</head>

<body>

    <!-- START NAV -->
    <nav class="navbar is-white">
        <div class="container">
            <div class="navbar-brand">
                <a class="logo" asp-controller="Pharmacies" asp-action="Index">
                    <b class="has-text-info">KHK Med</b>
                </a>
                <div class="navbar-burger burger" data-target="navMenu">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
            <div id="navMenu" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" asp-controller="Pharmacies" asp-action="Index">
                        Lékárny
                    </a>
                    <a class="navbar-item" asp-controller="Emergencies" asp-action="Index">
                        Pohotovosti
                    </a>
                    <a class="navbar-item" href="#">
                        Polikliniky
                    </a>
                </div>
                <div class="nav-menu-right">
                    <partial name="_LoginPartial" />
                </div>

            </div>
        </div>
    </nav>
    <!-- END NAV -->
    <div class="container">
        <div class="columns">
            <div class="column is-12">
                @RenderBody()
            </div>
        </div>
    </div>
    <script async type="text/javascript" src="~/js/bulma.js"></script>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>

</html>